application: form-crade
version: 1
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: django
  version: "1.3"

builtins:
- django_wsgi: on

handlers:
- url: /static/admin
  static_dir: static/admin
  expiration: '0'

- url: /crades
  static_dir: static/styles
  expiration: '0'